apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: hello-world-service
  labels:
    app: load-balancer-example
spec:
  type: LoadBalancer
  selector:
    app: load-balancer-example
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
