// Generated by ChatGPT
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <arpa/inet.h>

#define PORT 8080
#define RESPONSE_TEMPLATE \
    "HTTP/1.1 200 OK\r\n" \
    "Content-Length: %zu\r\n" \
    "Content-Type: text/plain\r\n" \
    "Connection: close\r\n" \
    "\r\n%s"

int main(int argc, char *argv[]) {
    if (argc != 3) {
        fprintf(stderr, "Usage: %s <url_path> <response_content>\n", argv[0]);
        exit(1);
    }

    const char *url_path = argv[1];
    const char *content = argv[2];

    int server_fd, client_fd;
    struct sockaddr_in addr;
    socklen_t addrlen = sizeof(addr);

    char buffer[4096];
    char response[8192];

    if ((server_fd = socket(AF_INET, SOCK_STREAM, 0)) == -1) {
        perror("socket");
        exit(1);
    }

    int opt = 1;
    if (setsockopt(server_fd, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt)) == -1) {
        perror("setsockopt");
        close(server_fd);
        exit(1);
    }

    addr.sin_family = AF_INET;
    addr.sin_addr.s_addr = INADDR_ANY;
    addr.sin_port = htons(PORT);

    if (bind(server_fd, (struct sockaddr *)&addr, sizeof(addr)) == -1) {
        perror("bind");
        close(server_fd);
        exit(1);
    }

    if (listen(server_fd, 10) == -1) {
        perror("listen");
        close(server_fd);
        exit(1);
    }

    for (;;) {
        if ((client_fd = accept(server_fd, (struct sockaddr *)&addr, &addrlen)) == -1) {
            perror("accept");
            continue;
        }

        ssize_t bytes_read = read(client_fd, buffer, sizeof(buffer) - 1);
        if (bytes_read <= 0) {
            close(client_fd);
            continue;
        }
        buffer[bytes_read] = '\0';

        char method[8], path[1024];
        sscanf(buffer, "%7s %1023s", method, path);

        if (strcmp(method, "GET") == 0 && strcmp(path, url_path) == 0) {
            snprintf(response, sizeof(response), RESPONSE_TEMPLATE, strlen(content), content);
            write(client_fd, response, strlen(response));
        } else {
            const char *not_found = "HTTP/1.1 404 Not Found\r\n"
                                    "Content-Length: 0\r\n"
                                    "Connection: close\r\n\r\n";
            write(client_fd, not_found, strlen(not_found));
        }

        close(client_fd);
    }

    close(server_fd);
    return 0;
}
